# Generated by Django 6.0 on 2025-12-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_remove_booking_guest_booking_address_booking_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'Confirmed'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
